### ISSUE TITLE
Cookie Error!!

### ISSUE THREAD

**Issue by nishkarsh-shastri** [yuhonglin/YTCrawl#1]
I am trying to batch_crawl a file of 50,000 video ids on which some are invalid. But Everytime I try to batch_crawl that file I get this error. Sometimes there is http error also. My net connection is working fine but under a proxy address. 

  File "video_view.py", line 11, in <module>
    c.batch_crawl("9_50000","log")
  File "/home/nishkarsh/YTCrawl/crawler.py", line 320, in batch_crawl
    self.update_cookie_and_sectiontoken()
  File "/home/nishkarsh/YTCrawl/crawler.py", line 144, in update_cookie_and_sectiontoken
    self.period_update()
  File "/home/nishkarsh/YTCrawl/crawler.py", line 189, in period_update
    raise Exception('meet error when update the cookies, please set a new seed video (%s)' % str(e))

Any idea how I can get over it? Is it related to cookie? Is there any way to clear the cookies and start afresh?

**Comment by yuhonglin** [comment]
Hi Nishkarsh,
Thanks for reporting this. But you only pasted the information of where the exception was raised. Can you paste all the exception information? It should be below the sentence "raise Exception('meet error when update the cookies, please set a new seed video (%s)' % str(e))"

**Comment by nishkarsh-shastri** [comment]
REPORTING AGAIN

Traceback (most recent call last):
  File "video_view.py", line 11, in <module>
    c.batch_crawl("8_50000","log")
  File "/home/nishkarsh/YTCrawl/crawler.py", line 320, in batch_crawl
    self.update_cookie_and_sectiontoken()
  File "/home/nishkarsh/YTCrawl/crawler.py", line 144, in update_cookie_and_sectiontoken
    self.period_update()
  File "/home/nishkarsh/YTCrawl/crawler.py", line 189, in period_update
    raise Exception('meet error when update the cookies, please set a new seed video (%s)' % str(e))
Exception: meet error when update the cookies, please set a new seed video ([Errno 104] Connection reset by peer)

DOING IT AGAIN 
nishkarsh@nishkarsh-pc:~*******************//timeBasedStats$ python video_view.py 
Traceback (most recent call last):
  File "video_view.py", line 11, in <module>
    c.batch_crawl("8_50000","log")
  File "/home/nishkarsh/YTCrawl/crawler.py", line 320, in batch_crawl
    self.update_cookie_and_sectiontoken()
  File "/home/nishkarsh/YTCrawl/crawler.py", line 144, in update_cookie_and_sectiontoken
    self.period_update()
  File "/home/nishkarsh/YTCrawl/crawler.py", line 189, in period_update
    raise Exception('meet error when update the cookies, please set a new seed video (%s)' % str(e))
Exception: meet error when update the cookies, please set a new seed video (<urlopen error [Errno 104] Connection reset by peer>)

**Comment by yuhonglin** [comment]
I have tried and googled for a while. It seems:
1. the crawler still works on my computer.
2. your error(104) seems to be fatal. Some people point out that it is because a server disconnect with you.

I suspect it is your proxy causing this. If possible, please try another network. 

May I ask another question: have you crawled some of the videos, or you can not get anything at all? If you get something before you meet the error, it is maybe because you have requested too frequently --- this crawler will request about 10 times per second.

**Comment by nishkarsh-shastri** [comment]
Yes, I think it is because of proxy error. But I would like it to run in an infinite loop till I establish the connection. But I can't seem to find the proper source code to do that. If I do that for Batch Crawl only then the same exception keep on ocurring. Should I introduce more sleep to get the connection right?

Unfortunately I don't have any other connection other than this proxy one.  

About the second question:
None of the videos are crawled in the given file. The batch crawl creates the files to write upon but none of the logs get filled.
But I have used it to crawl 25000 videos from another file. But in this file, the errror is persisting.
A help regarding the sleep time to crawl again would help greatly.

**Comment by yuhonglin** [comment]
I have updated the code. See https://github.com/yuhonglin/YTCrawl#configuration to change the two parameters, e.g. set a bigger delay time and have a try.

**Comment by nishkarsh-shastri** [comment]
Still the proxy problem persists. I guess it can't be helped. Thanks for the help. I will try some bigger delay and get back to you.
